### ISSUE TITLE
How to build the app via Xcode?

### ISSUE THREAD

**Issue by Ein-Tim** [eu-digital-green-certificates/dgca-verifier-app-ios#44]
## Your Question?

* Source File: [README.md](https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios/blob/main/README.md)
* Line(s): [README.md - Developement](https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios/blob/main/README.md#development)
* Question: I'm quite a newbie to Xcode and would like to build the project. The build fails with "Missing package product 'SwiftDGC'". Am I doing something wrong or is the project not yet ready to be build? 

Thank you for answering and thank you for making this whole process Open-Source! 
I'm looking forward to a good cooperation with you, like at the Corona-Warn-App project!

**Comment by yspreen** [comment]
Hey Ein-Tim, thanks for the issue!

This is something we overlooked, and it is fixed in a feature branch already. I'll make sure to get it merged ASAP. In the meantime, you can read the instructions here: https://github.com/eu-digital-green-certificates/dgca-verifier-app-ios/blob/fix/readme/README.md

**Comment by yspreen** [comment]
The short answer is: clone the core module into the same folder that you cloned the verifier into :)

**Comment by Ein-Tim** [comment]
Thank you @yspreen. I'll try that and then report back here.

**Comment by Ein-Tim** [comment]
After I cloned the core module into the same folder, it's working now. Thank you for your help!
